# Core colors
cursor     #cccac2
foreground #cccac2
background #0b0e14

# Normal colors
color0  #1e232b
color1  #ed8274
color2  #87d96c
color3  #facc6e
color4  #6dcbfa
color5  #dabafa
color6  #90e1c6
color7  #c7c7c7

# Bright colors
color8  #686868
color9  #f28779
color10 #d5ff80
color11 #ffd173
color12 #73d0ff
color13 #dfbfff
color14 #95e6cb
color15 #ffffff

# Tabs
tab_bar_background        #171b24
active_tab_foreground     #171b24
active_tab_background     #c7c7c7
inactive_tab_background   #171b24
inactive_tab_foreground   #c7c7c7

# Selection
selection_foreground      #171b24
selection_background      #c7c7c7

# Borders
active_border_color       #c7c7c7
inactive_border_color     #171b24
