# Core colors
cursor     #d3c6aa
foreground #d3c6aa
background #1e2326

# Normal colors
color0  #475258
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa

# Bright colors
color8  #859289
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa

# Tabs
tab_bar_background        #1e2326
active_tab_foreground     #1e2326
active_tab_background     #a7c080
inactive_tab_background   #1e2326
inactive_tab_foreground   #d3c6aa

# Selection
selection_foreground      #1e2326
selection_background      #a7c080

# Borders
active_border_color       #a7c080
inactive_border_color     #475258
