-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-green-cursors")
hl.env("XCURSOR_THEME", "catppuccin-mocha-green-cursors")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
